spin_version = "1"
authors = ["itowlson <ivan.towlson@fermyon.com>"]
description = "Spin ActivityPub implementation"
name = "activity-demo"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[variables]
# `username` may need to be changed on rebuild to defeat caching (which is rude
# but is something to figure  out later!)
username = { default = "alice3" }
public_key = { default = "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvdCBzYcXRKavTMv3qB46\n/FelDlfdQJV2wg/Ys4RRFFWiOBaODP9IEvik9faSfSHR0ArgUi1p9e9EnqFauN9A\nQU8zgnYNGn6Hvg2j2aG1oF7dsNxAQZwbtWRleh/ZFGB7uE+zqSxQE0GumUI2LEbI\n6nc1yXO4ySRpRjyJM4F++JZ6+ZFjzWHXabXTY5NthsuBGxn/+LsxZtVXklg85PCz\nQhDEleiUY7xF7TGRLLgDU4gh4tahqoBLeBpVqNIExvL06uCPrsN5toFDYt3VR3z2\n5vPhl4sivp154s6xhdL6A+xupDBKWJjq4VTzzzexvSj0bvh9gThAQrMz2HpIIc2c\nSwIDAQAB\n-----END PUBLIC KEY-----\n" }

[[component]]
id = "webfinger"
source = "webfinger/target/wasm32-wasi/release/webfinger.wasm"
[component.trigger]
route = "/.well-known/webfinger"
[component.config]
username = "{{ username }}"
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "webfinger"

[[component]]
id = "actor"
source = "actor/target/wasm32-wasi/release/actor.wasm"
[component.trigger]
route = "/actor"
[component.config]
username = "{{ username }}"
public_key = "{{ public_key }}"
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "actor"

# Planning to use this for profile picture etc. but not figured out where that goes yet!
[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.1/spin_static_fs.wasm", digest = "sha256:650376c33a0756b1a52cad7ca670f1126391b79050df0321407da9c741d32375" }
id = "static"
files = [ { source = "assets", destination = "/" } ]
[component.trigger]
route = "/static/..."
